[package]
name = "paxlovid-tauri"
version = "1.0.0"
description = "Paxlovid Standalone Interaction Checker"
authors = ["TMU ER"]
edition = "2021"

[lib]
name = "paxlovid_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["custom-protocol"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-clipboard-manager = "2"
